name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Configure Environment for CI
        run: |
          sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=sqlite/" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=:memory:/" .env
          touch database/database.sqlite

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Setup Database
        run: php artisan migrate --force

      - name: Tests
        run: ./vendor/bin/pest
